### ISSUE TITLE
Don't hardcode port 8080

### ISSUE THREAD

**Issue by FranklinChen** [Gabriel439/servant-crud#1]
I couldn't run the demo out of the box because I already have something running on port 8080.

**Comment by Gabriella439** [comment]
I took a stab at this, and it works, but I'm still reluctant to change this example because then the client bindings need to be pulled underneath the `main` function.  I want people who read this example to learn that you can have top-level bindings to an external API.

Also, it's not that hard to change the client and server to use a different port.

**Comment by FranklinChen** [comment]
My concern is that a newcomer who wants to try running this thing out the box will think "Haskell sucks, you have to hardcode the port". Seriously, this is the kind of question or reaction I get when presenting any demo code in Haskell, so I've learned that things should Just Work. Most demos of similar things for other languages allow specifying the port through a command line or environment variable.

**Comment by Gabriella439** [comment]
That's a good point.  Then I'll make the port configurable later tonight.
